name: my_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter
  camera: ^0.11.1
  image_picker: ^1.1.2
  image_picker_for_web: 3.0.6
  flutter_sound: ^9.28.0
  path_provider: ^2.0.15
  permission_handler: 11.4.0

  cupertino_icons: ^1.0.2
  flutter_lints: ^6.0.0
  http: ^1.4.0
  open_file: ^3.5.10
  dio: ^5.6.0
  video_player: ^2.4.7  # 视频播放
  chewie: ^1.3.5        # 视频播放UI
  audio_session: ^0.1.9 # 音频配置
  cached_network_image: ^3.2.3 # 图片缓存
  file_picker: ^10.2.0   # 文件选择(可选)
  provider: ^6.0.5
  flutter_markdown: ^0.7.7+1
  intl: ^0.20.2
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1 
  universal_html: ^2.2.4
  universal_web: ^1.1.1
  convert: ^3.1.2
  just_audio: ^0.10.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/background.jpg
    - assets/icon.png
    - assets/Group 222.png
    - assets/Group 227.png
    - assets/Group 228.png
    - assets/icon2.png
    - assets/aa.png
    - assets/ab.png
    - assets/ac.png
    - assets/ad.png
    - assets/mush.png
    - assets/
    - assets/learning_video.mp4